export const EXERCISES_ERRORED = 'EXERCISES_ERRORED';
export const EXERCISES_LOADING = 'EXERCISES_LOADING';
export const EXERCISES_SUCCEEDED = 'EXERCISES_SUCCEEDED';
export const SELECT_EXERCISE = 'SELECT_EXERCISE';
