export const EXERCISES_FAILED = 'EXERCISES_FAILED';
export const EXERCISES_LOADING = 'EXERCISES_LOADING';
export const EXERCISES_SUCCEEDED = 'EXERCISES_SUCCEEDED';

export const SELECT_EXERCISE = 'SELECT_EXERCISE';

export const LOGS_SUCCEEDED = 'LOGS_SUCCEEDED';
export const LOGS_LOADING = 'LOGS_LOADING';
export const LOGS_FAILED = 'LOGS_FAILED';

export const SHOW_LOG_INFO = 'SHOW_LOG_INFO';

export const INPUT_EXERCISE = 'INPUT_EXERCISE';
export const NEW_EXERCISE_SUCCEEDED = 'NEW_EXERCISE_SUCCEEDED';
export const NEW_EXERCISE_FAILED = 'NEW_EXERCISE_FAILED';
export const NEW_EXERCISE_LOADING = 'NEW_EXERCISE_LOADING';

export const OPEN_MODAL = 'OPEN_MODAL';
export const INPUT_LOG = 'INPUT_LOG';
export const PICK_IMAGE = 'PICK_IMAGE';
export const NEW_LOG_LOADING = 'NEW_LOG_LOADING';
export const NEW_LOG_SUCCEEDED = 'NEW_LOG_SUCCEEDED';
export const NEW_LOG_FAILED = 'NEW_LOG_FAILED';
export const RESET_NEW_LOG_FORM = 'RESET_NEW_LOG_FORM';

export const INPUT_LOGIN = 'INPUT_LOGIN';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';

export const PROFILE_SUCCEEDED = 'PROFILE_SUCCEEDED';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_FAILED = 'PROFILE_FAILED';

export const INPUT_USER = 'INPUT_USER';
export const CREATE_USER = 'CREATE_USER';
