export const EXERCISES_FAILED = 'EXERCISES_FAILED';
export const EXERCISES_LOADING = 'EXERCISES_LOADING';
export const EXERCISES_SUCCEEDED = 'EXERCISES_SUCCEEDED';
export const SELECT_EXERCISE = 'SELECT_EXERCISE';
export const LOGS_SUCCEEDED = 'LOGS_SUCCEEDED';
export const LOGS_LOADING = 'LOGS_LOADING';
export const LOGS_FAILED = 'LOGS_FAILED';
export const SHOW_LOG_INFO = 'SHOW_LOG_INFO';
